services:
  server:
    build: ./server
    container_name: mogocounts-server
    restart: always
    environment:
      - MONGODB_URI=mongodb://mongo:27017/mogocounts
      - PORT=3003
    ports:
      - "3003:3003"
    networks:
      - nginx-raspberry_app-network

  client:
    build: ./client
    container_name: mogocounts-client
    restart: always
    ports:
      - "4003:4003"
    depends_on:
      - server
    networks:
      - nginx-raspberry_app-network

networks:
  nginx-raspberry_app-network:
    external: true
